name: Deploy Discord Commands

on:
  push:
    branches:
      - main

jobs:
  deploy-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://vercel.com/guides/corepack-errors-github-actions#1.-if-you%E2%80%99re-on-node-18+-or-newer
      - name: Use Latest Corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          pnpm --version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build bot
        run: pnpm build:bot

      - name: Deploy Commands
        run: pnpm register-commands
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          INDEXABLE_CHANNEL_IDS: ''
          REVALIDATE_SECRET: ''
          WEB_URL: ''
